// The Juice Score methodology page: docs/LIVABILITY.md rendered as a page of
// the site itself, so "How it's calculated" never leaves the site.
//
//   static build:  dist/methodology/index.html + dist/methodology/methodology.css
//   server mode:   GET /methodology/ and /methodology/methodology.css
//                  (server/index.js; same renderer, so both modes match)
//
// renderMethodologyPage({ md, sha }) -> HTML string. Asset and app links are
// relative to the page ("../styles.css", "../"), so it works under the Pages
// sub-path and at /methodology/ on the server. CSP-clean: no inline script or
// style elements (styles come from methodology.css).
import { mdToHtml, esc } from './md.js';

/** Files under docs/ that the page may link to (by their site path). Everything else -> text. */
const SITE_LINKS = new Map([
  ['../data/cities.json', '../api/cities.json'], // the published copy of the data
]);

/** Link policy for the rendered doc: keep in-site targets, turn the rest into text. */
function linkFor(href) {
  if (SITE_LINKS.has(href)) return SITE_LINKS.get(href);
  return null;
}

export const METHODOLOGY_CSS = `/* melon-seek methodology page (generated by scripts/methodology.js). Uses the site's tokens. */
.doc-page { max-width: 880px; margin: 0 auto; padding: 24px 20px 64px; color: var(--ms-text); font-family: var(--ms-font); line-height: 1.6; }
.doc-top { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 12px 20px; border-bottom: 1px solid var(--ms-border); background: var(--ms-surface); position: sticky; top: 0; z-index: 2; }
.doc-top a { color: var(--ms-accent); font-weight: 600; text-decoration: none; }
.doc-top a:hover { text-decoration: underline; }
.doc-brand { display: inline-flex; align-items: center; gap: 8px; color: var(--ms-text) !important; }
.doc-page h1 { font-size: 1.9rem; line-height: 1.2; margin: 8px 0 12px; }
.doc-page h2 { font-size: 1.35rem; margin: 40px 0 10px; padding-top: 8px; border-top: 1px solid var(--ms-border); }
.doc-page h3 { font-size: 1.1rem; margin: 28px 0 8px; }
.doc-page h1, .doc-page h2, .doc-page h3, .doc-page h4 { scroll-margin-top: 72px; }
.doc-page .anchor { opacity: 0; margin-left: 6px; color: var(--ms-muted); text-decoration: none; font-weight: 400; }
.doc-page :is(h1, h2, h3, h4):hover .anchor, .doc-page .anchor:focus { opacity: 1; }
.doc-page :target { background: var(--ms-amber-bg, transparent); }
.doc-page a { color: var(--ms-accent); }
.doc-page code { font-family: var(--ms-mono); font-size: 0.88em; background: var(--ms-surface-2); padding: 1px 5px; border-radius: 4px; }
.doc-page pre { background: var(--ms-surface-2); border: 1px solid var(--ms-border); border-radius: var(--ms-radius-sm, 6px); padding: 12px 14px; overflow-x: auto; }
.doc-page pre code { background: none; padding: 0; }
.doc-page .table-wrap { overflow-x: auto; margin: 12px 0; }
.doc-page table { border-collapse: collapse; font-size: 0.9rem; min-width: 60%; }
.doc-page th, .doc-page td { border: 1px solid var(--ms-border); padding: 6px 10px; vertical-align: top; text-align: left; }
.doc-page th { background: var(--ms-surface-2); }
.doc-page blockquote { margin: 12px 0; padding: 4px 14px; border-left: 3px solid var(--ms-border-strong, var(--ms-border)); color: var(--ms-muted); }
.doc-page .ref-url { color: var(--ms-muted); font-size: 0.85em; word-break: break-all; }
.doc-toc { background: var(--ms-surface); border: 1px solid var(--ms-border); border-radius: var(--ms-radius-sm, 6px); padding: 10px 16px; margin: 16px 0 8px; }
.doc-toc ol { margin: 4px 0; padding-left: 20px; }
.doc-note { color: var(--ms-muted); font-size: 0.9rem; }
.doc-foot { margin-top: 48px; padding-top: 12px; border-top: 1px solid var(--ms-border); color: var(--ms-muted); font-size: 0.85rem; }
`;

/**
 * @param {{ md: string, sha?: string|null }} opts
 * @returns {string} a complete HTML page
 */
export function renderMethodologyPage({ md, sha = null } = {}) {
  const { html, headings } = mdToHtml(md, { link: linkFor });
  const title = (headings.find((h) => h.level === 1) || { text: 'Juice Score methodology' }).text;
  const toc = headings.filter((h) => h.level === 2)
    .map((h) => `<li><a href="#${esc(h.id)}">${esc(h.text)}</a></li>`).join('');
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(title)} — melon·seek</title>
  <meta name="description" content="How melon·seek's Juice Score is calculated: the formula, tax model, data sources and limitations.">
  <meta name="color-scheme" content="light dark">
  <link rel="icon" href="../favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="../styles.css">
  <link rel="stylesheet" href="methodology.css">
  <script src="../theme-init.js"></script>
</head>
<body>
  <nav class="doc-top" aria-label="Site">
    <a class="doc-brand" href="../"><img src="../favicon.svg" alt="" width="22" height="22"> melon·seek</a>
    <a href="../">← Back to the jobs</a>
  </nav>
  <main class="doc-page">
    <p class="doc-note">The method behind the Juice Score shown in each job's drawer. An estimate, not financial advice.</p>
    ${toc ? `<nav class="doc-toc" aria-label="Contents"><strong>Contents</strong><ol>${toc}</ol></nav>` : ''}
    ${html}
    <footer class="doc-foot">Rendered from <code>docs/LIVABILITY.md</code>${sha ? ` at build <code>${esc(String(sha).slice(0, 12))}</code>` : ''}. Source references are shown as text; open them yourself if you want to check a figure. <a href="../">Back to melon·seek</a>.</footer>
  </main>
</body>
</html>
`;
}
